Logical: FRLMCorpsDocumentIPS	
Id: fr-lm-corps-document-ips					
Title: "Modèle logique métier - FR LM Corps document IPS"				
Description: "Eléments métier du corps d'une Synthèse Médicale (International Patient Summary) contenant l'ensemble des sections cliniques et administratives."	

* problemesActifs 1..1 FRLMProblemesActifs "Section Problèmes Actifs"
* antecedentsMedicaux  0..1 FRLMAntecedentsMedicaux "Section Antécédents médicaux"
* historiqueDesActes 1..1 FRLMHistoriqueDesActes "Section Historique des actes"
* allergiesEtHypersensibilites 1..1 FRLMAllergiesEtHypersensibilites  "Section Allergies et hypersensibilités"
* effetsIndesirables 0..1 FRLMEffetsIndesirables "Section Effets indésirables"
* traitements 1..1 FRLMTraitement "Section Traitement"
* dispositifsMedicaux  1..1 FRLMDispositifsMedicaux "Section Dispositifs médicaux"
* pointsDeVigilancesNonCode 0..1 FRLMPointsDeVigilancesNonCode "Section Points de Vigilances non codé"
* statutFonctionnel 0..1 FRLMStatutFonctionnel "Section Statut fonctionnel"
* signesVitaux 0..1 FRLMSignesVitaux "Section Signes vitaux"
* habitusModeDeVie 0..1 FRLMHabitusModeDeVie "Section Habitus et modes de vie"
* antecedentsFamiliaux  0..1 FRLMAntecedentsFamiliaux "Section Antécédents familiaux"
* facteursDeRisqueProfessionnelsNonCode  0..1 FRLMFacteursDeRisqueProfessionnelsNonCode "Section Facteurs de risque professionnels non Codé"
* vaccinations 0..1 FRLMVaccinations "Section Vaccinations"
* historiqueDesGrossesses 0..1 FRLMHistoriqueDesGrossesses "Section Historique des grossesses"
* planSoins 0..1 FRLMPlanSoins "Section Plan de Soins"
* directivesAnticipees 0..1 FRLMDirectivesAnticipees "Section Directives anticipées"
* resultats 0..1 FRLMResultats "Section Resultats"
* documentsAjoutes 0..1 FRLMDocumentsAjoutes "Section Documents ajoutés" 