Logical: FRLMEnteteDocumentIPS
Id: fr-lm-entete-document-ips					
Title: "Modèle logique métier - FR LM En-tête document IPS"				
Description: "Éléments d'en-tête spécifiques au Document de Synthèse Patient IPS (International Patient Summary) : identification et type du document, patient/usager, auteur, évènement documenté, etc..."
* . 1..1	
* identifiantUniqueDocument 1..1 Identifier "Identifiant unique du document."
* modeleDocument 1..1 Identifier "Modèle du document et version du modèle."
* typeDocument 1..1 CodeableConcept "Type de document."	
* titreDocument 1..1 string "Titre du document."			
* dateDeCreationDocument 1..1 dateTime "Date de création du document."				
* niveauConfidentialiteDocument 1..1 code  "Niveau de confidentialité du document."				
* languePrincipaleDocument 1..1 code "Langue principale du document."
* identifiantLotDeVersionsDocument  1..1 Identifier  "Identifiant du lot de versions du même document."		
* versionDocument 1..1 string "Numéro de version du document."
* statutDocument 1..1 code "Statut du document."
* patient 0..* FRLMPatientUsager "Patient / Usager."
* auteur 1..* FRLMAuteur "Auteur du document."
* operateurSaisie 0..1 FRLMOperateurSaisie "Opérateur de saisie."	
* informateur 0..* FRLMInformateur "Informateur ayant fourni des informations utiles à la production du document."	
* structureConservation 1..1 FRLMStructureConservation "Structure chargée de la conservation du document."	
* destinataire 0..* FRLMDestinatairePrevu "Destinataire prévu du document."	
* responsable 0..* FRLMResponsable "Responsable du document."	
* validateur 0..* FRLMValidateur "PS attestant la validité du document."							
* participant 0..* FRLMParticipant "Participant, jouant dans l'édition du document, un rôle différent de celui d'auteur, de responsable, d'opérateur de saisie, d'informateur ou de destinataire."							
* evenement 1..1 FRLMEvenement "Evènement documenté et notamment le cadre d'exercice."				
* documentDeReference 0..* FRLMDocumentDeReference "Document de référence (à remplacer, transformé, …)."
* priseEncharge 1..1 FRLMPriseEncharge "Association du document à une prise en charge."			